services:
  app:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /dev/log:/dev/log
      - app_logs:/app/todo_project/logs
    working_dir: /app/todo_project
    command: >
      sh -c "pip install --no-cache-dir -r /app/requirements.txt && python run.py"

  loki:
    image: grafana/loki:3.4.2
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.4.2
    volumes:
      - ./config/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - app_logs:/logs:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./config/grafana/alerting:/etc/grafana/provisioning/alerting:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  app_logs:
  loki_data:
  grafana_data:
