{
 "title": "App Logs - Task Manager",
 "tags": [
  "flask",
  "task-manager"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Timeline de Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"flask-app\"}"
    }
   ]
  },
  {
   "title": "LOGIN_FAILURE por minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({job=\"flask-app\"} |= \"LOGIN_FAILURE\" [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "LOGIN_SUCCESS por minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({job=\"flask-app\"} |= \"LOGIN_SUCCESS\" [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Tasks Criadas (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"flask-app\"} |= \"OPERATION_SUCCESS\" |= \"create\" [$__range])"
    }
   ]
  },
  {
   "title": "Acessos Não Autorizados (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"flask-app\"} |= \"UNAUTHORIZED_ACCESS\" [$__range])"
    }
   ]
  },
  {
   "title": "Eventos por Severidade (24h)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({job=\"flask-app\"} | regexp \"(INFO|WARNING|ERROR)\" [$__range]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Falhas de Login (último minuto) — Alerta Brute-force",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"flask-app\"} |= \"LOGIN_FAILURE\" [1m])",
     "legendFormat": "LOGIN_FAILURE/min"
    }
   ]
  }
 ]
}